SELECT
    ROUND(LATITUDE, 1) AS LAT_BUCKET,
    ROUND(LONGITUDE, 1) AS LON_BUCKET,
    COUNT(*) AS TOTAL_EVENTS,
    COUNT(DISTINCT MMSI) AS UNIQUE_VESSELS
FROM AIS_MARITIME_DB.SILVER.SILVER_VESSEL_POSITIONS_CLEAN
GROUP BY 1, 2
