SELECT
    DATE_TRUNC('hour', EVENT_TIMESTAMP) AS EVENT_HOUR,
    AVG(SPEED) AS AVG_SPEED,
    MAX(SPEED) AS MAX_SPEED,
    COUNT(*) AS TOTAL_EVENTS
FROM AIS_MARITIME_DB.SILVER.SILVER_VESSEL_POSITIONS_CLEAN
WHERE SPEED IS NOT NULL
GROUP BY 1
