SELECT
    MMSI,
    SHIP_NAME,
    COUNT(*) AS TOTAL_MESSAGES,
    COUNT(DISTINCT DATE_TRUNC('hour', EVENT_TIMESTAMP)) AS ACTIVE_HOURS
FROM AIS_MARITIME_DB.SILVER.SILVER_VESSEL_POSITIONS_CLEAN
GROUP BY 1, 2
ORDER BY TOTAL_MESSAGES DESC
LIMIT 50
