SELECT
    MMSI,
    SHIP_NAME,
    MAX(SPEED) AS MAX_SPEED,
    AVG(SPEED) AS AVG_SPEED,
    COUNT(*) AS TOTAL_EVENTS
FROM AIS_MARITIME_DB.SILVER.SILVER_VESSEL_POSITIONS_CLEAN
WHERE SPEED > 0
GROUP BY 1, 2
ORDER BY MAX_SPEED DESC
LIMIT 50
